---
title: 'Project Milestone #5'
author: "Cian Stryker"
date: "10/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readxl)
library(reshape2)
library(plyr)
library(countrycode)
library(janitor)
library(maps)
library(ggmap)
library(gganimate)
library(tidyverse)
```

```{r, message=FALSE}
Chinese_FDI <- read_excel("raw-data/Chinese_Investment_and_Construction.xlsx", skip = 4) %>%
  clean_names()

Chinese_FDI$country <- countrycode(Chinese_FDI$country, "country.name", "country.name")
```

```{r warning=FALSE}
map.world <- map_data('world')
colnames(map.world)[colnames(map.world) == 'region'] <- 'country'
map.world$country <- countrycode(map.world$country, "country.name", "country.name")

```

ap.oil <- left_join( map.world, df.oil, by = c('region' = 'country')) 

x5 <- merge(x4, Pr_1, by = c("year", "country")) %>%
```{r, warning=FALSE}
China_test <- Chinese_FDI %>%
  select("year", `quantity_in_millions`, "country") 
  
China_test1 <- aggregate(quantity_in_millions ~ country + year, data = China_test, FUN = sum)

China_test2 <- China_test1 %>%
  complete(year, nesting(country), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(country) %>%
  mutate(y_cum4 = cumsum(quantity_in_millions)) %>%
  filter(year == 2019)

workss <- left_join(map.world, China_test2, by = c("country"))
```

```{r, warning=FALSE}
ggplot(workss, aes( x = long, y = lat, group = group )) +
  geom_polygon(aes(fill = y_cum4)) +
  guides(fill = guide_legend(reverse = T,)) +
  labs(fill = 'Commulative FDI'
       ,title = 'Commulative Chinese Foreign Direct Investment by Country'
       ,subtitle = '2019'
       ,x = NULL
       ,y = NULL) +
  theme(text = element_text(family = 'Gill Sans', color = '#333333')
        ,plot.title = element_text(size = 18)
        ,plot.subtitle = element_text(size = 14)
        ,axis.ticks = element_blank()
        ,axis.text = element_blank()
        ,panel.grid = element_blank()
        ,plot.background = element_rect(fill = '#CCCCCC')
        ,legend.position = c(.18,.36)
        ,legend.background = element_rect(fill = '#CCCCCC')
        ,legend.key = element_blank()
        ) +
  annotate(geom = 'text'
           ,label = 'Source: Us Chamber of Commerce'
           ,x = 18, y = -55
           ,size = 3
           ,family = 'Gill Sans'
           ,color = '#333333'
           ,hjust = 'left'
           )
```

```{r, message=FALSE}
China_simple <- Chinese_FDI %>%
  select("year", "quantity_in_millions")

China_simple_1 <- aggregate(quantity_in_millions ~ year, data = China_simple, FUN = sum)

options(scipen=0)

ggplot(China_simple_1, aes(x = year, y = quantity_in_millions, fill = year)) +
  guides(fill = FALSE) +
  geom_col() +
  labs(
    title = "Chinese Direct Foreign Investment over Time",
    x = "FDI in Millions", 
    y = "Year"
  )
  
```

```{r}
China <- Chinese_FDI %>%
  select("year", `quantity_in_millions`, "country", "region") 
  
China_1 <- aggregate(quantity_in_millions ~ country + year + region, data = China, FUN = sum)
```

```{r}
China_1x <- China_1 %>%
  complete(year, nesting(country, region), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country) %>%
  mutate(y_cum = cumsum(quantity_in_millions))

ggplot(China_1x, aes(x = region, y = y_cum, fill = region)) +
  geom_col()+
  labs(x=NULL, y=NULL, fill=NULL, title="{closest_state}") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10)) +
  transition_states(year, transition_length = 2, state_length = 1) +
  enter_fade() + 
  guides(fill = FALSE) +
  ease_aes('sine-in-out') 
```

```{r}
China_sector <- Chinese_FDI %>%
    select("country", "region", "year", "sector", "quantity_in_millions") %>%
    filter(sector %in% c("Energy", "Real estate", "Metals", "Transport")) %>%
    filter(region %in% c("Arab Middle East and North Africa", "South America", "Europe", "North America", "Sub-Saharan Africa", "West Asia")) 
  
China_sector1 <- aggregate(quantity_in_millions ~ country + year + region + sector, data = China_sector, FUN = sum)

China_sector2 <- China_sector1 %>%
  complete(year, nesting(country, region, sector), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country, sector) %>%
  mutate(y_cum2 = cumsum(quantity_in_millions))

China_sector3 <- China_sector2 %>%
    filter(year == 2019)



ggplot(China_sector3, aes(x = sector, y = y_cum2, fill = region)) +
  geom_col() +
  labs(x = "BRI Sectors", y = "Investment by Sector", fill=NULL, title="Commulative BRI Investment by Sector: 2019") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 10)) +
  guides(fill = FALSE) +
  facet_wrap(~region)

China_sector10 <- aggregate(y_cum2 ~ country + year + region, data = China_sector3, FUN = sum)

```
